apiVersion: v1
kind: Template
metadata:
  name: comunes-email-api-config-template
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: comunes-email-api