create sequence DOMICILIO_ID_SEQ;
create sequence SEQ_DATOS_SEGUIMIENTO;
create sequence TELEFONO_ID_SEQ;
create sequence SEQ_OBSERVACION;


create table PARAMETRO(
	PARAMETRO_ID NUMBER(19) not null,
	CODIGO VARCHAR(50) not null,
	DESCRIPCION VARCHAR(200) not null,
	ID_DOMINIO_PARAMETRO NUMBER(19) not null,
);

create table DATOS_SEGUIMIENTO_PROCESO
(
	DATOS_SEGUIMIENTO_ID NUMBER(19) not null,
	ASIGNADO_A VARCHAR2(255 ),
	FINALIZADO_POR VARCHAR2(255),
	FECHA TIMESTAMP(6),
	DERIVADO_POR VARCHAR(255 char),
	DERIVADO_A VARCHAR(255 ),
	OBSERVACIONES VARCHAR(255 ),
	PROCESO_INSTANCIA_ID NUMBER(19),
	LIBERADO_POR VARCHAR2(255),
	TAREA_ID NUMBER(19),
	ID_SEGUIMIENTO_ACCION NUMBER(19) not null
);

create table TELEFONO
(
	TELEFONO_ID NUMBER(19) not null,
	PREFIJO VARCHAR2(5),
	NUMERO VARCHAR2(200),
	ACTIVO NUMBER(1) not null,
	ID_PARAM_TIPO_TELEFONO NUMBER(19) not null,
	INTERNO NUMBER(4)
);

create table DOMICILIO(
	DOMICILIO_ID NUMBER(19) not null,
	CALLE VARCHAR2(255),
	NUMERO VARCHAR2(10),
	PISO VARCHAR2(5),
	DEPARTAMENTO VARCHAR2(20),
	BARRIO VARCHAR2(50),
	MANZANA VARCHAR2(5),
	CASA VARCHAR2(5),
	TORRE VARCHAR2(5),
	CODIGO_POSTAL VARCHAR2(8),
	ID_PROVINCIA NUMBER(19),
	ENTRE_CALLE1 VARCHAR2(200),
	ACLARACION VARCHAR2(255),
	LATITUD NUMBER(10,6),
	LONGITUD NUMBER(10,6),
	ENTRE_CALLE2 VARCHAR2(200),
	CODIGO_POSTAL_ARGENTINO VARCHAR2(10),
	VALIDADO NUMBER(1),
	ERROR_VALIDACION NUMBER(1),
	PARTIDO_DESC VARCHAR2(255),
	LOCALIDAD_DESC VARCHAR2(255)
);

create table LOCALIDAD
(
	LOCALIDAD_ID NUMBER(19) not null,
	DESCRIPCION VARCHAR2(255),
	CODIGO_POSTAL VARCHAR2(8),
	ID_PARTIDO NUMBER(19),
	ID_LOCALIDAD_SSS NUMBER(19),
	ID_PROVINCIA NUMBER(19)
);

create table PARTIDO
(
	PARTIDO_ID NUMBER(19) not null,
	DESCRIPCION VARCHAR2(255),
	ID_PROVINCIA NUMBER(19) not null
);

create table OBSERVACION_PROCESO
(
	OBSERVACION_ID NUMBER(19) not null
		primary key,
	COMENTARIO VARCHAR2(1024 char),
	FECHA TIMESTAMP(6),
	PROCESO_INSTANCIA_ID NUMBER(19),
	USUARIO VARCHAR2(255 char)
);

create table PROVINCIA
(
	PROVINCIA_ID NUMBER(19) not null,
	DESCRIPCION VARCHAR2(255)
);


INSERT INTO PARTIDO (PARTIDO_ID, DESCRIPCION, ID_PROVINCIA) VALUES (1, 'BUENOS AIRES',1);
INSERT INTO LOCALIDAD (LOCALIDAD_ID, DESCRIPCION, CODIGO_POSTAL, ID_PARTIDO, ID_LOCALIDAD_SSS, ID_PROVINCIA) VALUES (1, 'EL ALGARROBO', '4434', 1, null, null);
INSERT INTO PROVINCIA (PROVINCIA_ID, DESCRIPCION) VALUES (1, 'BUENOS AIRES');
INSERT INTO DOMICILIO (DOMICILIO_ID, CALLE, NUMERO, PISO, DEPARTAMENTO, BARRIO, MANZANA, CASA, TORRE, CODIGO_POSTAL, ID_PROVINCIA, ENTRE_CALLE1, ACLARACION, LATITUD, LONGITUD, ENTRE_CALLE2, CODIGO_POSTAL_ARGENTINO, VALIDADO, ERROR_VALIDACION, PARTIDO_DESC, LOCALIDAD_DESC) VALUES
(0, '148', '2152', null, null, null, null, null, null, '1884', 2, null, null, null, null, null, '1884', 0, 0, 'BERAZATEGUI', 'BERAZATEGUI');
INSERT INTO PARAMETRO (PARAMETRO_ID, CODIGO, DESCRIPCION, ID_DOMINIO_PARAMETRO) VALUES (34, 'EXT', 'Externo', 10);
INSERT INTO PARAMETRO (PARAMETRO_ID, CODIGO, DESCRIPCION, ID_DOMINIO_PARAMETRO) VALUES (37, 'EMP', 'Empresa', 10);
INSERT INTO PARAMETRO (PARAMETRO_ID, CODIGO, DESCRIPCION, ID_DOMINIO_PARAMETRO) VALUES (36, 'OSO', 'Obra Social', 10);
INSERT INTO PARAMETRO (PARAMETRO_ID, CODIGO, DESCRIPCION, ID_DOMINIO_PARAMETRO) VALUES (35, 'GF', 'Grupo Familiar', 10);


