runCIPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn package -DskipTests -Dfabric8.skip -e -B",
			  analyzeCommands: "mvn sonar:sonar -DskipTests",
              testCommands: "sleep 5",
              artifactsDir: "./target")
